config/routes.rb
Airlines::Application.routes.draw do
  
  devise_for :clients

  resources :clients
  
  resources :class_types

  resources :categories

  resources :tickets

  resources :schedules

  resources :airplanes

  resources :cities

  resources :flights

  get "flights/index"

  get "flights/show"

  get "/flights/buy_tickets/:schedule_id", to: "flights#buy_tickets", as: "buy_tickets"

  post "/flights/reserve/", to: "flights#reserve", as: "reserve"

  get "home/index"

  root 'home#index'

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def show
    if City.find_by_name(params[:departure_city_id]).try(:id) and City.find_by_name(params[:arrival_city_id]).try(:id)
		  @departure = City.find_by_name(params[:departure_city_id]).id 
		  @arrival =  City.find_by_name(params[:arrival_city_id]).id

      if @departure == @arrival
        redirect_to flights_path, notice: 'Enter different cities'
      end
    else 
        redirect_to flights_path, notice: 'Path not found' 
    end

    @Schedules = Schedule.find(:all, :conditions => ["departure_city_id = ? and arrival_city_id in (?)", @departure, @arrival], :order => 'price ASC')
    
    @classTypeId = params[:class_type]
    #@classType = ClassType.find(classTypeId.to_s).name
    
 	end

  def buy_tickets
    @scheduleToBuy = Schedule.find_by_id(params[:schedule_id])
  end

  def reserve
    TicketMailer.buy_ticket(current_client.email).deliver
    redirect_to root_path, notice: 'You buy a ticket'
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<div class="jumbotron">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#RoundTrip" data-toggle="tab">One Way</a></li>
    <li><a href="#OneWay" data-toggle="tab">RoundTrip</a></li>
    <li><a href="#MultipleDestinations" data-toggle="tab">Multiple Destinations</a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane fade in active" id="RoundTrip">
        <!-- Formulario 1 -->
        <br>
        <%= form_tag(flights_show_path, :method => "get") do %>
        <div class="row-xs-height">
          <%= label_tag(:flyingFrom, "Flying From") %>
			    <%= text_field_tag :departure_city_id, params[:departure_city_id], placeholder: "Departure City" %>
          <%= label_tag(:flyingTo, "Flying To") %>
          <%= text_field_tag :arrival_city_id, params[:arrival_city_id], placeholder: "Arrival City" %>
        </div>
        <br>
        <div class="row-xs-height">
          <%= label_tag(:departing, "Departing") %>
          <%= date_field(:departing, :date) %>
          <%= label_tag(:retorning, "Retorning") %>
          <%= date_field(:retorning, :date) %>
        </div>
        <br>
        <div class="row-xs-height">
          <%= label_tag(:adults, "Adults (+18)") %>
          <%= number_field(:adults, :number, in: 1..6, step: 1) %>
          <%= label_tag(:children, "Children (0-17)") %>
          <%= number_field(:children, :number, in: 0..6, step: 1) %>
        </div>
        <br>
        <div class="row-xs-height">
          <%= label_tag(:nonstopL, "Nonstop") %>
          <%= check_box_tag(:nonstop) %>
          <%= label_tag(:PC, "Preferred Class") %>
          <%=collection_select(:class_type, :class_type, ClassType.all, :id, :name) %>
        </div>
        <br>
        <br>
        <br>
			  <%= submit_tag "Search", :name => nil, class: 'btn btn-info'%>			
		    <% end %>
    </div>
    <div class="tab-pane fade" id="OneWay">
      <br>
      <!-- Formulario 2 -->
      
    </div>
    <div class="tab-pane fade" id="MultipleDestinations">
      <br>
      <!-- Formulario 3 -->
      
    </div>
  </div>
</div>

app/views/flights/buy_tickets.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1><center>Selected flight</center></h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Departure time</th>
          <th>Arrival time</th>
          <th>Time</th>
          <th>Departure City</th>
          <th>Arrival City</th>
          <th>Airplane</th>
          <th>Price</th>
        </tr>
      </thead>

      <tbody>
        <td><%= @scheduleToBuy.departure_time.strftime("%I:%M%p") %></td>
            <td><%= @scheduleToBuy.arrival_time.strftime("%I:%M%p") %></td>
            <td><%= ((@scheduleToBuy.arrival_time - @scheduleToBuy.departure_time)/60).round %></td>
            <td><%= City.find_by_id(@scheduleToBuy.departure_city_id).name %></td>
            <td><%= City.find_by_id(@scheduleToBuy.arrival_city_id).name %></td>
            <td><%= Airplane.find_by_id(@scheduleToBuy.airplane_id).airplane_model %></td>
            <td>$<%= @scheduleToBuy.price %></td>
      </tbody>
    </table>

  <br>
  <br>
  <br>

  <% if client_signed_in? %>
  <div class="jumbotron" style="text-align:center">
    <h2>Datos de Usuario</h2><br>
    <h3>Nombre: <%= current_client.first_name %> <%= current_client.middle_name %></h3>
    <h3>Apellidos: <%= current_client.last_name %></h3>
    <h3>Pais de Origen: <%= current_client.nationality %></h3>
    <h3>Correo Electronico: <%= current_client.email %></h3>
    <br>
    <br>
    <%= link_to 'Reserve', reserve_path, class: 'btn btn-success' %>
  </div>
  <% end %>
  
</div>

app/views/flights/index.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Fligths</h1>

	<%= render 'form' %>
	<br><br>
	<%= link_to 'Back', root_path , class: 'btn btn-info' %>
</div>

app/views/flights/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Schedules</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Departure time</th>
        <th>Arrival time</th>
        <th>Time</th>
        <th>Departure City</th>
        <th>Arrival City</th>
        <th>Airplane</th>
        <th>Price</th>
        <th>Class Type</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @Schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.departure_time.strftime("%I:%M%p") %></td>
          <td><%= schedule.arrival_time.strftime("%I:%M%p") %></td>
          <td><%= ((schedule.arrival_time - schedule.departure_time)/60).round %></td>
          <td><%= City.find_by_id(schedule.departure_city_id).name %></td>
          <td><%= City.find_by_id(schedule.arrival_city_id).name %></td>
          <td><%= Airplane.find_by_id(schedule.airplane_id).airplane_model %></td>
          <td>$<%= schedule.price %></td>
          <td><%= ClassType.find_by_id(@classTypeId['class_type']).name %></td>
          <td><%= link_to 'Buy', buy_tickets_path(schedule), class: 'btn btn-sm btn-info'  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  
</div>