config/routes.rb
Airlines::Application.routes.draw do
  
  devise_for :clients

  resources :clients
  
  resources :class_types

  resources :categories

  resources :tickets

  resources :schedules

  resources :airplanes

  resources :cities

  resources :flights

  get "flights/index"

  get "flights/show"

  get "/flights/buy_tickets/:schedule_id", to: "flights#buy_tickets", as: "buy_tickets"

  post "/flights/reserve/", to: "flights#reserve", as: "reserve"

  get "home/index"

  root 'home#index'

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
	has_many :schedules
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :tickets
end

app/models/city.rb
class City < ActiveRecord::Base
	has_one :schedule
end

app/models/class_type.rb
class ClassType < ActiveRecord::Base
	has_many :tickets
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	# Relations
	belongs_to :departure_city, class_name: 'City', foreign_key: 'departure_city_id'
	belongs_to :arrival_city, class_name: 'City', foreign_key: 'arrival_city_id'
	belongs_to :airplane
	has_and_belongs_to_many :tickets

  #scope :search, ->(departure) { where(departure_city_id: City.find_by_name(departure) ) }

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	# Relations
	belongs_to :category
	belongs_to :class_type
	has_and_belongs_to_many :schedules
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_logged

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_url, notice: 'City was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_url, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Cheks if admin are signed in
    def check_admin_logged
      redirect_to new_client_session_path unless client_signed_in? and current_client.try(:admin)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def show
    if City.find_by_name(params[:departure_city_id]).try(:id) and City.find_by_name(params[:arrival_city_id]).try(:id)
		  @departure = City.find_by_name(params[:departure_city_id]).id 
		  @arrival =  City.find_by_name(params[:arrival_city_id]).id

      if @departure == @arrival
        redirect_to flights_path, notice: 'Enter different cities'
      end
    else 
        redirect_to flights_path, notice: 'Path not found' 
    end

    @Schedules = Schedule.find(:all, :conditions => ["departure_city_id = ? and arrival_city_id in (?)", @departure, @arrival], :order => 'price ASC')
    
    @classTypeId = params[:class_type]
    #@classType = ClassType.find(classTypeId.to_s).name
    
 	end

  def buy_tickets
    @scheduleToBuy = Schedule.find_by_id(params[:schedule_id])
  end

  def reserve
    TicketMailer.buy_ticket(current_client.email).deliver
    redirect_to root_path, notice: 'You buy a ticket'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home_layout'
  def index
  end  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_client!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:departure_date, :return_date, :class_type_id, :category_id)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/class_types_helper.rb
module ClassTypesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_navbar_admin.html.erb
<nav class="navbar navbar-inverse">
	<div class="navbar-header">
		<%= link_to 'Teguz Airlines', root_path, class: 'navbar-brand' %>
	</div>
	
	<ul class="nav navbar-nav">
		<li><%= link_to 'Cities', cities_path %></li>
		<li><%= link_to 'Airplanes', airplanes_path %></li>
		<li><%= link_to 'Schedules', schedules_path %></li>
		<li><%= link_to 'Categories', categories_path %></li>
		<li><%= link_to 'Class Types', class_types_path %></li>
	</ul>

</nav>

app/views/layouts/_navbar_home.html.erb
<nav class="navbar col-md-10 col-md-offset-1" id="navbar-home">
  <div class="navbar-header">
      <%= link_to root_path do %>
        <%= cl_image_tag 'logo-teguz_jndgkw.png', width: 170, height: 120, crop: :fill, class: 'img-responsive' %>
      <% end %>
  </div>

  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to 'Search flights', flights_path %></li>
    
    <% if client_signed_in? %>
      <% if current_client.try(:admin) %>
        <li><%= link_to 'Cities', cities_path %></li>
        <li><%= link_to 'Airplanes', airplanes_path %></li>
        <li><%= link_to 'Schedules', schedules_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <li><%= link_to 'Class Types', class_types_path %></li>
      <% end %>
      <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= icon 'caret-down', current_client.email %></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Sign out', destroy_client_session_path, method: :delete %></li>
        </ul>
      </li>

      <% else %>
      <li><%= link_to 'Sign up', new_client_registration_path, class: 'btn btn-primary navbar-btn' %></li>
      <li>
        <%= link_to '#', class: 'dropdown-toggle btn btn-info', data: { toggle: 'dropdown' }  do %>
          <%= icon 'caret-down', 'Sign in' %>
        <% end %>

        <div class="dropdown-menu sign-in-form">
          <%= form_for(:client, url: session_path(:client), class: 'form-horizontal') do |f| %>
            <div class="form-group">
              <%= f.text_field :email, autofocus: true, placeholder: 'Email', class: 'form-control input-sm' %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, placeholder: 'Password', class: 'form-control input-sm' %>
            </div>
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
            <%= f.submit 'Sign in', class: 'btn btn-success btn-sm' %><br><br>
            <%= link_to "Forgot your password?", new_password_path(:client), class: 'btn btn-warning btn-sm' %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teguz Airlines</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar_admin' %>
  <% unless flash.empty?  %>
  	<div class="alert alert-warning col-md-8 col-md-offset-2 alert-dismissable">
  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  		<%= flash.notice %>
	</div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teguz Airlines</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="big-banner">
      <%= render partial: 'layouts/navbar_home' %>
      <%= yield %>
   </div>

</body>
</html>